version: "3.7"

services:
  dyndbcounter:
    container_name: dyndbcounter
    image: amazon/dynamodb-local
    restart: unless-stopped
    networks:
      - counter 
    ports:
      - 8000:8000

networks:
  counter:
    external: true
