version: "3.7"

services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    restart: unless-stopped
    networks:
      - dyn
    ports:
      - 8000:8000

networks:
  dyn:
    external: true
