version: "3.7"

services:
  dynadmin:
    container_name: dynadmin
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: "dynamodb:8000"
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "dynamodblocal"
      AWS_SECRET_ACCESS_KEY: "dynamodblocal"
    restart: unless-stopped
    networks:
      - dyn
    ports:
      - 8001:8001
networks:
  dyn:
    external: true
