version: "3.7"

services:
  dynadmin_counter:
    container_name: dynadmin_counter
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: "dyndbcounter:8000"
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "dynamodblocal"
      AWS_SECRET_ACCESS_KEY: "dynamodblocal"
    restart: unless-stopped
    networks:
      - counter
    ports:
      - 8001:8001
networks:
  counter:
    external: true
